INSERT INTO `menus` (`id`, `menu_name`, `parent_id`, `lft`, `rght`, `controller`, `action`, `icon_class_name`, `is_hidden`, `query_string`, `target`) VALUES
(1,	'Dashboard',	NULL,	1,	2,	'Logins',	'index',	'fa fa-home',	'N',	'',	''),
(2,	'Masters',	NULL,	3,	48,	'#',	'#',	'fa fa-gears',	'N',	'',	''),
(3,	'Customer',	2,	4,	13,	'#',	'#',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(4,	'Add',	3,	5,	6,	'Customers',	'add',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(5,	'Edit',	3,	7,	8,	'Customers',	'index',	'glyphicon glyphicon-asterisk',	'N',	'edt',	''),
(6,	'Delete',	3,	9,	10,	'Customers',	'index',	'glyphicon glyphicon-asterisk',	'N',	'del',	''),
(7,	'Search',	3,	11,	12,	'Customers',	'index',	'glyphicon glyphicon-asterisk',	'N',	'ser',	''),
(8,	'Supplier',	2,	49,	58,	'#',	'#',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(9,	'Add',	8,	50,	51,	'Suppliers',	'add',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(10,	'Edit',	8,	52,	53,	'Suppliers',	'index',	'glyphicon glyphicon-asterisk',	'N',	'edt',	''),
(11,	'Delete',	8,	54,	55,	'Suppliers',	'index',	'glyphicon glyphicon-asterisk',	'N',	'del',	''),
(12,	'Search',	8,	56,	57,	'Suppliers',	'index',	'glyphicon glyphicon-asterisk',	'N',	'ser',	''),
(13,	'Employee',	2,	59,	68,	'#',	'#',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(14,	'Add',	13,	60,	61,	'Employees',	'add',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(15,	'Edit',	13,	62,	63,	'Employees',	'index',	'glyphicon glyphicon-asterisk',	'N',	'edt',	''),
(16,	'Delete',	13,	64,	65,	'Employees',	'index',	'glyphicon glyphicon-asterisk',	'N',	'del',	''),
(17,	'Search',	13,	66,	67,	'Employees',	'index',	'glyphicon glyphicon-asterisk',	'N',	'ser',	''),
(18,	'Car',	2,	69,	72,	'#',	'#',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(19,	'Add',	18,	73,	74,	'Cars',	'add',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(20,	'Edit',	18,	75,	76,	'Cars',	'index',	'glyphicon glyphicon-asterisk',	'N',	'edt',	''),
(21,	'Delete',	18,	77,	78,	'Cars',	'index',	'glyphicon glyphicon-asterisk',	'N',	'del',	''),
(22,	'Search',	18,	70,	71,	'Cars',	'index',	'glyphicon glyphicon-asterisk',	'N',	'ser',	''),
(23,	'Customer Tariff',	2,	14,	23,	'#',	'#',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(24,	'Add',	23,	15,	16,	'CustomerTariffs',	'add',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(25,	'Edit',	23,	17,	18,	'CustomerTariffs',	'index',	'glyphicon glyphicon-asterisk',	'N',	'edt',	''),
(26,	'Delete',	23,	19,	20,	'CustomerTariffs',	'index',	'glyphicon glyphicon-asterisk',	'N',	'del',	''),
(27,	'Search',	23,	21,	22,	'CustomerTariffs',	'index',	'glyphicon glyphicon-asterisk',	'N',	'ser',	''),
(28,	'Supplier Tariff',	2,	24,	33,	'#',	'#',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(29,	'Add',	28,	25,	26,	'SupplierTariffs',	'add',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(30,	'Edit',	28,	27,	28,	'SupplierTariffs',	'index',	'glyphicon glyphicon-asterisk',	'N',	'edt',	''),
(31,	'Delete',	28,	29,	30,	'SupplierTariffs',	'index',	'glyphicon glyphicon-asterisk',	'N',	'del',	''),
(32,	'Search',	28,	31,	32,	'SupplierTariffs',	'index',	'glyphicon glyphicon-asterisk',	'N',	'ser',	''),
(33,	'Service',	2,	34,	39,	'#',	'#',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(34,	'Add',	33,	35,	36,	'Services',	'add',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(35,	'Edit | Delete | View',	33,	37,	38,	'Services',	'index',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(36,	'Counter',	2,	40,	41,	'Counters',	'add',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(37,	'Car Type',	2,	42,	43,	'CarTypes',	'index',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(38,	'Supplier Type',	2,	44,	45,	'SupplierTypes',	'index',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(39,	'Sub Supplier Type',	2,	46,	47,	'SupplierTypes',	'supplier',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(40,	'Duty Slip',	NULL,	79,	88,	'#',	'#',	'glyphicon glyphicon-list-alt',	'N',	'',	''),
(41,	'Add',	40,	80,	81,	'DutySlips',	'add',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(42,	'Edit',	40,	82,	83,	'DutySlips',	'index',	'glyphicon glyphicon-asterisk',	'N',	'edt',	''),
(43,	'Waveoff',	40,	84,	85,	'DutySlips',	'index',	'glyphicon glyphicon-asterisk',	'N',	'del',	''),
(44,	'Search',	40,	86,	87,	'DutySlips',	'index',	'glyphicon glyphicon-asterisk',	'N',	'ser',	''),
(45,	'Reports',	NULL,	89,	98,	'#',	'#',	'glyphicon glyphicon-folder-open',	'N',	'',	''),
(46,	'Waveoff Duty Slip',	45,	90,	91,	'DutySlips',	'waveoffds',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(47,	'Open DS',	45,	92,	93,	'DutySlips',	'OpenDs',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(48,	'Unbilled DS',	45,	94,	95,	'DutySlips',	'Unbilledds',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(49,	'Records',	45,	96,	97,	'DutySlips',	'records',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(50,	'Security',	NULL,	99,	108,	'#',	'#',	'glyphicon glyphicon-briefcase',	'N',	'',	''),
(51,	'User Right',	50,	100,	107,	'#',	'#',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(52,	'Add New User',	51,	101,	102,	'Logins',	'add',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(53,	'User Wise Rights',	51,	103,	104,	'UserRights',	'add',	'glyphicon glyphicon-asterisk',	'N',	'',	''),
(54,	'View Rights',	51,	105,	106,	'Logins',	'LoginView',	'glyphicon glyphicon-asterisk',	'N',	'',	'');